//<ref *1> Client {
//  _events: [Object: null prototype] {
//    shardDisconnect: [Function (anonymous)],
//    clientReady: [AsyncFunction (anonymous)],
//    guildCreate: [AsyncFunction (anonymous)],
//    guildMemberAdd: [AsyncFunction (anonymous)]
//  },
//  _eventsCount: 4,
//  _maxListeners: undefined,
//  options: {
//    closeTimeout: 5000,
//    waitGuildTimeout: 15000,
//    shardCount: 1,
//    makeCache: [Function (anonymous)],
//    partials: [],
//    failIfNotExists: true,
//    enforceNonce: false,
//    presence: { status: 'online', user: [Object] },
//    sweepers: { threads: [Object] },
//    ws: { large_threshold: 50, version: 10, presence: [Object] },
//    rest: {
//      agent: null,
//      api: 'https://discord.com/api',
//      authPrefix: 'Bot',
//      cdn: 'https://cdn.discordapp.com',
//      headers: {},
//      invalidRequestWarningInterval: 0,
//      globalRequestsPerSecond: 50,
//      offset: 50,
//      rejectOnRateLimit: null,
//      retries: 3,
//      timeout: 15000,
//      userAgentAppendix: 'discord.js/14.27.0 Node.js/24.20.0',
//      version: '10',
//      hashSweepInterval: 14400000,
//      hashLifetime: 86400000,
//      handlerSweepInterval: 3600000,
//      makeRequest: [AsyncFunction: makeRequest],
//      mediaProxy: 'https://media.discordapp.net'
//    },
//    jsonTransformer: [Function: toSnakeCase],
//    intents: IntentsBitField { bitfield: 3 },
//    shards: [ 0 ]
//  },
//  rest: REST {
//    _events: [Object: null prototype] {},
//    _eventCount: 0,
//    _maxListeners: 10,
//    _internalPromiseMap: Map(0) {},
//    _wrapperId: 0n,
//    agent: null,
//    cdn: CDN {
//      cdn: 'https://cdn.discordapp.com',
//      mediaProxy: 'https://media.discordapp.net'
//    },
//    globalRemaining: 49,
//    globalDelay: null,
//    globalReset: 1788211127490,
//    hashes: Collection(1) [Map] { 'GET:/gateway/bot' => [Object] },
//    handlers: Collection(1) [Map] {
//      'Global(GET:/gateway/bot):global' => [SequentialHandler]
//    },
//    hashTimer: Timeout {
//      _idleTimeout: 14400000,
//      _idlePrev: [TimersList],
//      _idleNext: [Timeout],
//      _idleStart: 92,
//      _onTimeout: [Function (anonymous)],
//      _timerArgs: undefined,
//      _repeat: 14400000,
//      _destroyed: false,
//      Symbol(refed): false,
//      Symbol(kHasPrimitive): false,
//      Symbol(asyncId): 8,
//      Symbol(triggerId): 0,
//      Symbol(kAsyncContextFrame): undefined
//    },
//    handlerTimer: Timeout {
//      _idleTimeout: 3600000,
//      _idlePrev: [Timeout],
//      _idleNext: [Timeout],
//      _idleStart: 92,
//      _onTimeout: [Function (anonymous)],
//      _timerArgs: undefined,
//      _repeat: 3600000,
//      _destroyed: false,
//      Symbol(refed): false,
//      Symbol(kHasPrimitive): false,
//      Symbol(asyncId): 9,
//      Symbol(triggerId): 0,
//      Symbol(kAsyncContextFrame): undefined
//    },
//    options: {
//      agent: null,
//      api: 'https://discord.com/api',
//      authPrefix: 'Bot',
//      cdn: 'https://cdn.discordapp.com',
//      headers: {},
//      invalidRequestWarningInterval: 0,
//      globalRequestsPerSecond: 50,
//      offset: 50,
//      rejectOnRateLimit: null,
//      retries: 3,
//      timeout: 15000,
//      userAgentAppendix: 'discord.js/14.27.0 Node.js/24.20.0',
//      version: '10',
//      hashSweepInterval: 14400000,
//      hashLifetime: 86400000,
//      handlerSweepInterval: 3600000,
//      makeRequest: [AsyncFunction: makeRequest],
//      mediaProxy: 'https://media.discordapp.net'
//    },
//    Symbol(async-event-emitter.ts-capture-promise-rejections): true
//  },
//  ws: WebSocketManager {
//    _events: [Object: null prototype] {},
//    _eventsCount: 0,
//    _maxListeners: undefined,
//    gateway: 'wss://gateway.discord.gg/',
//    shards: Collection(1) [Map] { 0 => [WebSocketShard] },
//    status: 0,
//    destroyed: false,
//    _ws: WebSocketManager {
//      _events: [Object: null prototype],
//      _eventCount: 8,
//      _maxListeners: 10,
//      _internalPromiseMap: Map(0) {},
//      _wrapperId: 0n,
//      options: [Object],
//      gatewayInformation: [Object],
//      shardIds: [Array],
//      strategy: [SimpleShardingStrategy],
//      Symbol(async-event-emitter.ts-capture-promise-rejections): true
//    },
//    totalShards: 1,
//    Symbol(shapeMode): false,
//    Symbol(kCapture): false
//  },
//  actions: ActionsManager {
//    injectedUser: Symbol(djs.actions.injectedUser),
//    injectedChannel: Symbol(djs.actions.injectedChannel),
//    injectedMessage: Symbol(djs.actions.injectedMessage),
//    client: [Circular *1],
//    ApplicationCommandPermissionsUpdate: ApplicationCommandPermissionsUpdateAction { client: [Circular *1] },
//    AutoModerationActionExecution: AutoModerationActionExecutionAction { client: [Circular *1] },
//    AutoModerationRuleCreate: AutoModerationRuleCreateAction { client: [Circular *1] },
//    AutoModerationRuleDelete: AutoModerationRuleDeleteAction { client: [Circular *1] },
//    AutoModerationRuleUpdate: AutoModerationRuleUpdateAction { client: [Circular *1] },
//    ChannelCreate: ChannelCreateAction { client: [Circular *1] },
//    ChannelDelete: ChannelDeleteAction { client: [Circular *1] },
//    ChannelUpdate: ChannelUpdateAction { client: [Circular *1] },
//    EntitlementCreate: EntitlementCreateAction { client: [Circular *1] },
//    EntitlementDelete: EntitlementDeleteAction { client: [Circular *1] },
//    EntitlementUpdate: EntitlementUpdateAction { client: [Circular *1] },
//    GuildAuditLogEntryCreate: GuildAuditLogEntryCreateAction { client: [Circular *1] },
//    GuildBanAdd: GuildBanAdd { client: [Circular *1] },
//    GuildBanRemove: GuildBanRemove { client: [Circular *1] },
//    GuildChannelsPositionUpdate: GuildChannelsPositionUpdate { client: [Circular *1] },
//    GuildDelete: GuildDeleteAction { client: [Circular *1] },
//    GuildEmojiCreate: GuildEmojiCreateAction { client: [Circular *1] },
//    GuildEmojiDelete: GuildEmojiDeleteAction { client: [Circular *1] },
//    GuildEmojiUpdate: GuildEmojiUpdateAction { client: [Circular *1] },
//    GuildEmojisUpdate: GuildEmojisUpdateAction { client: [Circular *1] },
//    GuildIntegrationsUpdate: GuildIntegrationsUpdate { client: [Circular *1] },
//    GuildMemberRemove: GuildMemberRemoveAction { client: [Circular *1] },
//    GuildMemberUpdate: GuildMemberUpdateAction { client: [Circular *1] },
//    GuildRoleCreate: GuildRoleCreate { client: [Circular *1] },
//    GuildRoleDelete: GuildRoleDeleteAction { client: [Circular *1] },
//    GuildRoleUpdate: GuildRoleUpdateAction { client: [Circular *1] },
//    GuildRolesPositionUpdate: GuildRolesPositionUpdate { client: [Circular *1] },
//    GuildScheduledEventCreate: GuildScheduledEventCreateAction { client: [Circular *1] },
//    GuildScheduledEventDelete: GuildScheduledEventDeleteAction { client: [Circular *1] },
//    GuildScheduledEventUpdate: GuildScheduledEventUpdateAction { client: [Circular *1] },
//    GuildScheduledEventUserAdd: GuildScheduledEventUserAddAction { client: [Circular *1] },
//    GuildScheduledEventUserRemove: GuildScheduledEventUserRemoveAction { client: [Circular *1] },
//    GuildSoundboardSoundDelete: GuildSoundboardSoundDeleteAction { client: [Circular *1] },
//    GuildStickerCreate: GuildStickerCreateAction { client: [Circular *1] },
//    GuildStickerDelete: GuildStickerDeleteAction { client: [Circular *1] },
//    GuildStickerUpdate: GuildStickerUpdateAction { client: [Circular *1] },
//    GuildStickersUpdate: GuildStickersUpdateAction { client: [Circular *1] },
//    GuildUpdate: GuildUpdateAction { client: [Circular *1] },
//    InteractionCreate: InteractionCreateAction { client: [Circular *1] },
//    InviteCreate: InviteCreateAction { client: [Circular *1] },
//    InviteDelete: InviteDeleteAction { client: [Circular *1] },
//    MessageCreate: MessageCreateAction { client: [Circular *1] },
//    MessageDelete: MessageDeleteAction { client: [Circular *1] },
//    MessageDeleteBulk: MessageDeleteBulkAction { client: [Circular *1] },
//    MessagePollVoteAdd: MessagePollVoteAddAction { client: [Circular *1] },
//    MessagePollVoteRemove: MessagePollVoteRemoveAction { client: [Circular *1] },
//    MessageReactionAdd: MessageReactionAdd { client: [Circular *1] },
//    MessageReactionRemove: MessageReactionRemove { client: [Circular *1] },
//    MessageReactionRemoveAll: MessageReactionRemoveAll { client: [Circular *1] },
//    MessageReactionRemoveEmoji: MessageReactionRemoveEmoji { client: [Circular *1] },
//    MessageUpdate: MessageUpdateAction { client: [Circular *1] },
//    PresenceUpdate: PresenceUpdateAction { client: [Circular *1] },
//    StageInstanceCreate: StageInstanceCreateAction { client: [Circular *1] },
//    StageInstanceDelete: StageInstanceDeleteAction { client: [Circular *1] },
//    StageInstanceUpdate: StageInstanceUpdateAction { client: [Circular *1] },
//    ThreadCreate: ThreadCreateAction { client: [Circular *1] },
//    ThreadDelete: ThreadDeleteAction { client: [Circular *1] },
//    ThreadListSync: ThreadListSyncAction { client: [Circular *1] },
//    ThreadMemberUpdate: ThreadMemberUpdateAction { client: [Circular *1] },
//    ThreadMembersUpdate: ThreadMembersUpdateAction { client: [Circular *1] },
//    TypingStart: TypingStart { client: [Circular *1] },
//    UserUpdate: UserUpdateAction { client: [Circular *1] },
//    VoiceStateUpdate: VoiceStateUpdate { client: [Circular *1] },
//    WebhooksUpdate: WebhooksUpdate { client: [Circular *1] }
//  },
//  voice: ClientVoiceManager { adapters: Map(0) {} },
//  shard: null,
//  users: UserManager {},
//  guilds: GuildManager {},
//  channels: ChannelManager {},
//  sweepers: Sweepers {
//    options: { threads: [Object] },
//    intervals: {
//      autoModerationRules: null,
//      applicationCommands: null,
//      bans: null,
//      emojis: null,
//      entitlements: null,
//      invites: null,
//      guildMembers: null,
//      messages: null,
//      presences: null,
//      reactions: null,
//      stageInstances: null,
//      stickers: null,
//      threadMembers: null,
//      threads: Timeout {
//        _idleTimeout: 3600000,
//        _idlePrev: [TimersList],
//        _idleNext: [Timeout],
//        _idleStart: 96,
//        _onTimeout: [Function (anonymous)],
//        _timerArgs: undefined,
//        _repeat: 3600000,
//        _destroyed: false,
//        Symbol(refed): false,
//        Symbol(kHasPrimitive): false,
//        Symbol(asyncId): 10,
//        Symbol(triggerId): 0,
//        Symbol(kAsyncContextFrame): undefined
//      },
//      users: null,
//      voiceStates: null
//    }
//  },
//  presence: ClientPresence {
//    userId: null,
//    guild: null,
//    status: 'online',
//    activities: [],
//    clientStatus: null
//  },
//  user: ClientUser {
//    id: '924708782313984000',
//    bot: true,
//    system: false,
//    flags: UserFlagsBitField { bitfield: 65536 },
//    username: 'Pronoun bot',
//    globalName: null,
//    discriminator: '3937',
//    avatar: 'ef04ac44c0d940135fcdc600054f368d',
//    banner: undefined,
//    accentColor: undefined,
//    avatarDecoration: null,
//    avatarDecorationData: null,
//    collectibles: null,
//    primaryGuild: null,
//    verified: true,
//    mfaEnabled: true
//  },
//  application: <ref *2> ClientApplication {
//    id: '924708782313984000',
//    name: null,
//    description: null,
//    icon: null,
//    termsOfServiceURL: null,
//    privacyPolicyURL: null,
//    rpcOrigins: [],
//    cover: null,
//    verifyKey: null,
//    tags: [],
//    installParams: null,
//    integrationTypesConfig: null,
//    customInstallURL: null,
//    flags: ApplicationFlagsBitField { bitfield: 27312128 },
//    approximateGuildCount: null,
//    approximateUserInstallCount: null,
//    approximateUserAuthorizationCount: null,
//    guildId: null,
//    botRequireCodeGrant: null,
//    bot: null,
//    botPublic: null,
//    interactionsEndpointURL: null,
//    roleConnectionsVerificationURL: null,
//    eventWebhooksURL: null,
//    eventWebhooksStatus: null,
//    eventWebhooksTypes: null,
//    owner: null,
//    commands: ApplicationCommandManager {
//      permissions: [ApplicationCommandPermissionsManager]
//    },
//    emojis: ApplicationEmojiManager { application: [Circular *2] },
//    entitlements: EntitlementManager {},
//    subscriptions: SubscriptionManager {}
//  },
//  readyTimestamp: 1788211132851,
//  commands: Collection(2) [Map] {
//    'profile' => { data: [SlashCommandBuilder], execute: [AsyncFunction: execute] },
//    'update' => { data: [SlashCommandBuilder], execute: [AsyncFunction: execute] }
//  },
//  Symbol(shapeMode): false,
//  Symbol(kCapture): true
//}
